name: Release

on: 
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

permissions:
  contents: write

jobs:
  buildAndRelease:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    container: gcc:13

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
    
    # Update references
    - name: Git Sumbodule Update
      run: |
        git config --global --add safe.directory /__w/C2LinuxImplant/C2LinuxImplant
        git submodule update --init
        
    - name: Get Conan
      # You may pin to the exact commit or the version.
      # uses: turtlebrowser/get-conan@c171f295f3f507360ee018736a6608731aa2109d
      uses: turtlebrowser/get-conan@v1.2

    - name: Create default profile
      run: conan profile detect
      
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DWITH_TESTS=OFF -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=${{github.workspace}}/conan_provider.cmake

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 18

    - name: Prep release
      shell: pwsh
      run: |
        rm .\Release\Beacons\.gitignore
        mv .\Release\Beacons .\Release\LinuxBeacons
        rm .\Release\Modules\.gitignore
        mv .\Release\Modules .\Release\LinuxModules
        Compress-Archive -Path .\Release -DestinationPath .\Release.zip

    - name: Upload release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Release.zip
        asset_name: Release.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "Linux beacons and modules"

