name: Release

on: 
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

permissions:
  contents: write

jobs:
  buildAndRelease:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    container: gcc:13

    steps:
    - uses: actions/checkout@v4

    - name: Install system dep
      run: |
        apt update -y
        apt install -y cmake
        apt install -y python3-pip
      shell: bash
    
    # Update references
    - name: Git Sumbodule Update
      run: |
        git config --global --add safe.directory /__w/C2LinuxImplant/C2LinuxImplant
        git submodule update --init
        
    - name: Get Conan
      run: |
        pip3 install conan --break-system-packages
      shell: bash

    - name: Create default profile
      run: conan profile detect
      
    - name: Configure CMake
      run: cmake -B /__w/C2LinuxImplant/C2LinuxImplant/build -DWITH_TESTS=OFF -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=/__w/C2LinuxImplant/C2LinuxImplant/conan_provider.cmake

    - name: Build
      run: cmake --build /__w/C2LinuxImplant/C2LinuxImplant/build --config ${{env.BUILD_TYPE}} -j 18

    - name: Prep release
      shell: bash
      run: |
        rm .\Release\Beacons\.gitignore
        mv .\Release\Beacons .\Release\LinuxBeacons
        rm .\Release\Modules\.gitignore
        mv .\Release\Modules .\Release\LinuxModules
        tar -zcvf Release.tar.gz Release

    - name: Upload release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Release.tar.gz
        asset_name: Release.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
        body: "Linux beacons and modules"

